config/routes.rb
Rails.application.routes.draw do
  get 'profiles/show'
  get 'criticisms/create'
  get 'criticisms/destroy'
  # https://stackoverflow.com/questions/3546289/override-devise-registrations-controller
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  authenticated :user do
    root 'articles#index', as: :authenticated_root
  end

  #https://stackoverflow.com/questions/4954876/setting-devise-login-to-be-root-page
  devise_scope :user do
    root to: "devise/sessions#new"
  end


  get 'profiles/:id', to: 'profiles#show', as: 'profile'

  resources :articles do
    resources :documents, only: [:create, :destroy]
    member do
      post 'upvote'
      post 'downvote'
    end
    resources :comments do
      resources :criticisms, only: [:create, :destroy]
      resources :documents 
      member do
        post 'upvote'
        post 'downvote'
      end
    
  end
  end

  get 'tags/search', to: 'tags#index'
  namespace :api do
    namespace :v1 do 
      devise_scope :user do
        post 'login', to: 'sessions#create'
        delete 'logout', to: 'sessions#destroy'
      end
      resources :articles

      resources :comments
      get 'comments/articles/:article', to: 'comments#getByArticle'

      get 'criticisms/:comment', to: 'criticisms#index'
      post 'criticisms', to: 'criticisms#create'
      delete 'criticisms/:id', to: 'criticisms#destroy'
    end
  end
end

app/models/criticism.rb
class Criticism < ApplicationRecord
  belongs_to :user
  belongs_to :comment

  validates :content, presence: true, length: { minimum: 10, maximum: 1000 }
end

app/controllers/api/v1/criticisms_controller.rb
module Api
    module V1
class CriticismsController < BaseController
    before_action :set_criticism, only: [:destroy]
    before_action :ensure_owner, only: [:destroy]
    #exception routes
    # skip_before_action :authenticate_user!, only: [:index, :show]
    
    def index
      @criticisms = Criticism.where(comment_id: params['comment'])
      render json: @criticisms
    end

    def create
      @user = User.find(@current_user_id)
      @criticism = @user.criticisms.build(criticism_params)
      if @criticism.save
        render json: @criticism, status: :created
      else
        render json: @criticism.errors, status: :unprocessable_entity
      end
    end

    def destroy   
      @criticism.destroy
      head :no_content
    end

    private
    def set_criticism
      @criticism = Criticism.find(params[:id])
    end
    def ensure_owner
      unless @criticism.user_id == @current_user_id
        render json: { error: 'You are not authorized to modify this criticism' }, status: :forbidden
      end
    end
  def criticism_params
    params.permit(:content, :comment_id, :criticism)
  end
end
end
end

app/controllers/criticisms_controller.rb
class CriticismsController < ApplicationController
  before_action :set_comment
  before_action :set_criticism, only: [:destroy]

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:comment_id])
    @criticism = @comment.criticisms.build(criticism_params)
    @criticism.user = current_user
  
    if @criticism.save
      redirect_to "#{article_path(@article)}#comment-section", notice: 'Criticism was successfully created.'
    else
      redirect_to "#{article_path(@article)}#comment-section", alert: 'Error creating criticism.'
    end
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:comment_id])
    @criticism = @comment.criticisms.find(params[:id])
    
    if @criticism.user == current_user
      @criticism.destroy
      redirect_to @article, notice: 'Criticism was successfully removed.'
    else
      redirect_to @article, alert: 'You are not authorized to remove this criticism.'
    end
  end

  private

  def set_comment
    @comment = Comment.find(params[:comment_id])
  end

  def set_criticism
    @criticism = @comment.criticisms.find(params[:id])
  end

  def criticism_params
    params.require(:criticism).permit(:content)
  end
end

app/helpers/criticisms_helper.rb
module CriticismsHelper
end

app/views/criticisms/_criticism.html.erb
<div class="bg-gray-50 rounded-lg p-3 mb-2">
    <p class="text-gray-800 mb-1"><%= criticism.content %></p>
    <div class="flex items-center justify-between text-xs">
      <span class="text-gray-600">By: <%= criticism.user.username %></span>
      <% if current_user == criticism.user %>
        <%= link_to 'Delete', article_comment_criticism_path(@article, comment, criticism),
            method: :delete,
            data: { confirm: 'Are you sure?' },
            class: "text-red-500 hover:text-red-700 transition-colors duration-200" %>
      <% end %>
    </div>
  </div>

app/views/criticisms/_form.html.erb
<div class="bg-gray-50 rounded-lg p-4 mt-4">
  <h5 class="text-lg font-semibold mb-3">Add a Criticism</h5>
  <%= form_with(model: [comment, Criticism.new], url: article_comment_criticisms_path(@article, comment), local: true) do |form| %>
    <div class="mb-4">
      <%= form.text_area :content, 
          class: "p-1 shadow-sm focus:ring-orange-500 focus:border-orange-500 mt-1 block w-full sm:text-sm border border-gray-300 rounded-md", 
          rows: 3, 
          placeholder: "Share your thoughts..." %>
    </div>
    <%= form.submit "Submit Criticism", 
        class: "inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-orange-600 hover:bg-orange-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-orange-500 transition duration-150 ease-in-out" %>
  <% end %>
</div>

app/views/criticisms/create.html.erb
<div>
  <h1 class="font-bold text-4xl">Criticisms#create</h1>
  <p>Find me in app/views/criticisms/create.html.erb</p>
</div>

app/views/criticisms/destroy.html.erb
<div>
  <h1 class="font-bold text-4xl">Criticisms#destroy</h1>
  <p>Find me in app/views/criticisms/destroy.html.erb</p>
</div>